server:
  port: 8383 # server publishing port number.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki_courses?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: salem_nabeel
    password: thinkoff10thinkoff
  jpa:
    show-sql: true # log jpa queries - only for testing purpose - [comment this in production].
    hibernate:
      ddl-auto: update # only for testing purpose - [comment this in production].
    properties:
      hibernate: # makes hibernate generate better sql for the chosen database.
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

# TODO: Using The Spring Boot Actuator